services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      GRANT_SUDO: "yes"
    user: root
    devices:
      - /dev/ttyACM0
    volumes:
      - ./scripts:/home/jovyan/work
    command: /bin/sh -c "start-notebook.sh --NotebookApp.token=''"
